## Create a filtered vcf for diem analysis
# vcffilt.sh
# ----------------------------------------------------------------------------------------------------------------------------------
#!/bin/bash -l
#SBATCH --job-name=vcffilt
#SBATCH --output=/dss/dsslegfs01/pn73qe/pn73qe-dss-0002/Formica_WGS/WGS_2024_2025/03.VCF/diem/logs/vcffilt_%j.out
#SBATCH --error=/dss/dsslegfs01/pn73qe/pn73qe-dss-0002/Formica_WGS/WGS_2024_2025/03.VCF/diem/logs/vcffilt_%j.err
#SBATCH --time=05:00:00
#SBATCH --get-user-env
#SBATCH --clusters=biohpc_gen
#SBATCH --partition=biohpc_gen_normal
#SBATCH --cpus-per-task=1
#SBATCH --mem=2GB
#SBATCH --mail-user=ada.crhonkova@seznam.cz
#SBATCH --mail-type=END,FAIL

# Load environment
eval "$(mamba shell hook --shell bash)"
mamba activate /dss/dsslegfs01/pn73qe/pn73qe-dss-0002/Formica_WGS/mamba_envs/bcftools.env

echo "Filtering Samples"

VCFPATH=/dss/dsslegfs01/pn73qe/pn73qe-dss-0002/Formica_WGS/WGS_2024_2025/03.VCF/raw
DIEMPATH=/dss/dsslegfs01/pn73qe/pn73qe-dss-0002/Formica_WGS/WGS_2024_2025/03.VCF/diem
VCFIN=all_samples.vcf.gz
vcftools --gzvcf $VCFPATH/$VCFIN \
  --keep $DIEMPATH/test1_3aq_3lu_3pol_3ru_diem.txt \
  --recode --recode-INFO-all \
  --stdout | bgzip > $DIEMPATH/data/test1_3aq_3lu_3pol_3ru_diem.vcf.gz

echo "Filtering Samples Done"
# ---------------------------------------------------------------------------------------------------------------------------------------
sacct -M biohpc_gen -j 4115586 --format=JobID,Elapsed,MaxRSS,AllocCPUS,State


# DATA POLARIZATION SCRIPT
# run_diem.py 
# ------------------------------------------------------------------------------------------------------------------
## packages
import numpy as np
np.set_printoptions(legacy = '1.25')

import pandas as pd

import matplotlib.pyplot as plt

import diempy as diem

import time
import sys
import os


# Path to vcf file
vcfFile = 'data/test1_3aq_3lu_3pol_3ru_diem.vcf.gz'
os.system('vcf2diem '+vcfFile)

# vcf2diem generated meta data file
metaRawFile = 'data/test1_3aq_3lu_3pol_3ru_diem.vcf.gz.diem_meta.bed'

# vcf2diem outputs a default ploidy of 2 and a relative recombination rate of 1.0
# following txt files serve to changing these preset values
#ploidyFile = 'user_files/iphiclides_ploidy_update.txt'
#recFile = 'user_files/relative_rec_rates.txt'

# corrected meta file 
#metaCorrected = 'data/iphiclides_example.vcf.gz.diem_meta_corrected.bed'

# correcting the meta file using variables specified above
#diem.update_meta(metaRawFile,metaCorrected,ploidyFilePath=ploidyFile,recFilePath=recFile)

## reading files
# input file (generated by vcf2diem)
bedInFile = 'data/test1_3aq_3lu_3pol_3ru_diem.vcf.gz.diem_input.bed'

# read the input file into diem object
dRaw = diem.read_diem_bed(bedInFile,metaRawFile)

# polarization
dPol = dRaw.polarize(ncores=4)

# set output file
bedOutFile = 'output/test1_3aq_3lu_3pol_3ru_diem_polarized.bed'
# saving as a .bed file with polarization information
diem.write_polarized_bed(bedInFile,bedOutFile,dPol)

# set diem output file; uses less memory, but is used only for diem analysis
polarizedDiemTypeOutFile = 'output/test1_3aq_3lu_3pol_3ru_diem_polarized.diemtype'
# saving as diem type object
diem.save_DiemType(dPol,polarizedDiemTypeOutFile)

## Call the diem script via bash script
# run_diem.sh
# ---------------------------- BASH JOB ---------------------------------------------------------------------------------------------

#!/bin/bash -l
#SBATCH --job-name=Diem
#SBATCH --output=/dss/dsslegfs01/pn73qe/pn73qe-dss-0002/Formica_WGS/WGS_2024_2025/03.VCF/diem/logs/Diem_%j.out
#SBATCH --error=/dss/dsslegfs01/pn73qe/pn73qe-dss-0002/Formica_WGS/WGS_2024_2025/03.VCF/diem/logs/Diem_%j.err
#SBATCH --time=05:00:00
#SBATCH --get-user-env
#SBATCH --clusters=biohpc_gen
#SBATCH --partition=biohpc_gen_normal
#SBATCH --cpus-per-task=4
#SBATCH --mem=8GB
#SBATCH --mail-user=ada.crhonkova@seznam.cz
#SBATCH --mail-type=END,FAIL

# Load environment
eval "$(mamba shell hook --shell bash)"
mamba activate /dss/dsslegfs01/pn73qe/pn73qe-dss-0002/Formica_WGS/mamba_envs/diempy

# change directory
cd /dss/dsslegfs01/pn73qe/pn73qe-dss-0002/Formica_WGS/WGS_2024_2025/03.VCF/diem

python /dss/dsslegfs01/pn73qe/pn73qe-dss-0002/Formica_WGS/WGS_2024_2025/03.VCF/diem/run_diem.py 

# ---------------------------- END OF BASH JOB -----------------------------------------------------------------------------------
sacct -M biohpc_gen -j 4123563 --format=JobID,Elapsed,MaxRSS,AllocCPUS,State

scp re98maw@cool.hpc.lrz.de:/dss/dsslegfs01/pn73qe/pn73qe-dss-0002/Formica_WGS/WGS_2024_2025/03.VCF/diem/output/test1_3aq_3lu_3pol_3ru_diem_polarized.diemtype .





